spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.167:3306/shenzhou?serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

